service: bloglog-extractor

provider:
  name: google
  stage: dev
  runtime: python37
  region: us-central1
  project: test-1-300600
  credentials: /mnt/c/users/brand/.gcloud/test-1-serverless.json

frameworkVersion: "2"
plugins:
  - serverless-google-cloudfunctions

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**

functions:
  extractor:
    handler: extract
    events:
      - http: path
